apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: taskmanager
  name: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: taskmanager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/shared-net: "true"
        io.kompose.service: taskmanager
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
          image: usermanager
          imagePullPolicy: ""
          name: taskmanager
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: taskmanager
  name: taskmanager
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: taskmanager
status:
  loadBalancer: {}