version: "3"
services:
  usermanagerc:
    image: 'usermanager'
    ports:
      - "8081:8081"
    container_name: usermanagerc
    environment:
      - "SPRING_PROFILES_ACTIVE=compose"
    links:
      - taskmanagerc
    depends_on:
      - taskmanagerc
    networks:
      - task-manager-network

  taskmanagerc:
    image: 'mongo'
    ports:
      - 27017:27017
    container_name: taskmanagerc
    volumes:
      - ./database:/database
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge