apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskmanagerdb
  name: taskmanagerdb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: taskmanagerdb
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanagerdb
  labels:
    app: taskmanagerdb
spec:
  selector:
    matchLabels:
      app: taskmanagerdb
  replicas: 1
  template:
    metadata:
      labels:
        app: taskmanagerdb
      name: taskmanagerdb-service
    spec:
      containers:
        - image: mongo:latest
          name: taskmanagerdb
          ports:
            - containerPort: 27017
              name: taskmanagerdb