spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?authSource=evolve&readPreference=primary&ssl=false
      database: taskmanager

server:
  port: 8082

management:
  server:
    port: 8082